version: "3"

services:
  photolink-postgres:
    container_name: photolink-postgres
    image: "postgres:14"
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      - DATABASE_HOST=${PG_HOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - photolink-postgres-storage:/var/lib/postgresql/data
    networks:
      - photolink

networks:
  photolink:
    driver: bridge

volumes:
  photolink-postgres-storage:
